# Environment Configuration
environment: "example-env"
hyperspace_account_id: ""

# Repository Configuration
vcsRepository: "https://github.com/<ORG>/<REPO>.git"
organization: ""
github_admin_team: ""
# Sync Policy Configuration
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true