apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecr-credentials-sync
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/<org>/<repo>.git
    targetRevision: main
    path: argocd/ecr-credentials-sync